# Generated by Django 3.0.4 on 2020-04-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, verbose_name='Nom')),
                ('nb_salles', models.IntegerField(verbose_name='Nombre de salles')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=5, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=20, verbose_name='Ville')),
                ('fermeture_exceptionnelle', models.CharField(max_length=100, verbose_name='Fermeture Exceptionnelle')),
            ],
            options={
                'verbose_name': 'Cinéma',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, verbose_name='Titre du film')),
                ('resume', models.TextField(verbose_name='Résumé du film')),
                ('classification', models.CharField(choices=[('ALL', 'Tous publics'), ('U12', 'Interdit aux moins de 12 ans'), ('U16', 'Interdit aux moins de 16 ans')], default='ALL', max_length=3)),
                ('affiche', models.FileField(upload_to='', verbose_name='Affiche du film')),
                ('cinemas', models.ManyToManyField(related_name='films_cinemas', to='cineseries.Cinema')),
            ],
            options={
                'verbose_name': 'Film',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salle', models.IntegerField(verbose_name='Numéro de salle')),
                ('date_seance', models.DateTimeField(verbose_name='Date et heure de la séance')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineseries.Cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineseries.Film')),
            ],
            options={
                'verbose_name': 'Séance',
                'ordering': ['date_seance'],
            },
        ),
        migrations.CreateModel(
            name='Ouverture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=10, verbose_name='Jour de la semaine')),
                ('heure_ouverture', models.TimeField(verbose_name='Heure douverture')),
                ('heure_fermeture', models.TimeField(verbose_name='Heure de fermeture')),
                ('cinemas', models.ManyToManyField(related_name='ouvertures_cinemas', to='cineseries.Cinema')),
            ],
            options={
                'verbose_name': 'Ouverture',
                'ordering': ['jour'],
            },
        ),
    ]
