# Generated by Django 3.0.4 on 2020-04-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0002_auto_20200417_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_genre', models.CharField(max_length=20, verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'ordering': ['libelle_genre'],
            },
        ),
        migrations.CreateModel(
            name='SeancesFilms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salle', models.IntegerField(verbose_name='Numéro de salle')),
                ('date_seance', models.DateTimeField(verbose_name='Date et heure de la séance')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Cinema')),
            ],
            options={
                'verbose_name': 'Séance',
                'ordering': ['date_seance'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_version', models.CharField(max_length=10, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Version',
                'ordering': ['libelle_version'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='note_moyenne',
            field=models.IntegerField(null=True, verbose_name='Note moyenne'),
        ),
        migrations.DeleteModel(
            name='Seance',
        ),
        migrations.AddField(
            model_name='seancesfilms',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Film'),
        ),
    ]
