# Generated by Django 3.0.4 on 2020-04-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0003_auto_20200417_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=20, null=True, verbose_name='Prénom')),
                ('sexe', models.CharField(max_length=1, null=True, verbose_name='Sexe')),
                ('date_naissance', models.DateTimeField(null=True, verbose_name='Date de naissance')),
                ('biographie', models.CharField(max_length=400, null=True, verbose_name='Biographie')),
                ('nb_films', models.IntegerField(null=True, verbose_name='Nombre de films')),
            ],
            options={
                'verbose_name': 'Acteur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('synopsis', models.TextField(null=True, verbose_name='Synopsis')),
                ('date_sortie', models.DateTimeField(null=True, verbose_name='Date de sortie')),
                ('affiche', models.FileField(null=True, upload_to='', verbose_name='Affiche')),
                ('duree', models.TimeField(null=True, verbose_name='Durée')),
                ('note_moyenne', models.IntegerField(null=True, verbose_name='Note moyenne')),
            ],
            options={
                'verbose_name': 'Episode',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, verbose_name='Numéro')),
                ('synopsis', models.TextField(null=True, verbose_name='Synopsis')),
                ('affiche', models.FileField(null=True, upload_to='', verbose_name='Affiche')),
                ('note_moyenne', models.IntegerField(null=True, verbose_name='Note moyenne')),
            ],
            options={
                'verbose_name': 'Saison',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('synopsis', models.TextField(null=True, verbose_name='Synopsis')),
                ('note_moyenne', models.IntegerField(null=True, verbose_name='Note moyenne')),
            ],
            options={
                'verbose_name': 'Série',
                'ordering': ['titre'],
            },
        ),
        migrations.AlterModelOptions(
            name='seancesfilms',
            options={'ordering': ['date_seance'], 'verbose_name': 'Séances films'},
        ),
        migrations.RenameField(
            model_name='film',
            old_name='duree_film',
            new_name='duree',
        ),
        migrations.AddField(
            model_name='realisateur',
            name='biographie',
            field=models.CharField(max_length=400, null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='realisateur',
            name='date_naissance',
            field=models.DateTimeField(null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='realisateur',
            name='nb_films',
            field=models.IntegerField(null=True, verbose_name='Nombre de films'),
        ),
        migrations.AddField(
            model_name='realisateur',
            name='prenom',
            field=models.CharField(max_length=20, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='realisateur',
            name='sexe',
            field=models.CharField(max_length=1, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='realisateur',
            name='nom',
            field=models.CharField(max_length=20, verbose_name='Nom'),
        ),
    ]
