# Generated by Django 3.0.4 on 2020-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0006_auto_20200417_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seancesfilm',
            options={'ordering': ['date_seance'], 'verbose_name': 'Séances film'},
        ),
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'ordering': ['user'], 'verbose_name': 'Informations utilisateur'},
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='cinemas',
            field=models.ManyToManyField(related_name='user_cinemas', to='cineseries.Cinema'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='films',
            field=models.ManyToManyField(related_name='user_films', to='cineseries.Film'),
        ),
    ]
