# Generated by Django 3.0.4 on 2020-04-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0007_auto_20200417_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'ordering': ['user'], 'verbose_name': 'Utilisateur'},
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='cinemas',
            field=models.ManyToManyField(null=True, related_name='user_cinemas', to='cineseries.Cinema'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='films',
            field=models.ManyToManyField(null=True, related_name='user_films', to='cineseries.Film'),
        ),
    ]
