# Generated by Django 3.0.4 on 2020-04-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0008_auto_20200417_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='date_naissance',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='date_sortie',
            field=models.DateField(null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.DateField(null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='realisateur',
            name='date_naissance',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='cinemas',
            field=models.ManyToManyField(blank=True, related_name='user_cinemas', to='cineseries.Cinema'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='user_films', to='cineseries.Film'),
        ),
    ]
