# Generated by Django 3.0.4 on 2020-04-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0009_auto_20200417_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='libelle',
            field=models.CharField(max_length=30, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='libelle',
            field=models.CharField(max_length=30, verbose_name='Genre'),
        ),
    ]
