# Generated by Django 3.0.4 on 2020-04-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0010_auto_20200417_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='libelle',
            field=models.CharField(max_length=40, verbose_name='Classification'),
        ),
    ]
