# Generated by Django 3.0.4 on 2020-04-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0011_auto_20200417_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='films_genres', to='cineseries.Genre'),
        ),
        migrations.AddField(
            model_name='seancesfilm',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cineseries.Version'),
        ),
        migrations.AddField(
            model_name='serie',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cineseries.Classification'),
        ),
        migrations.AddField(
            model_name='serie',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='series_genres', to='cineseries.Genre'),
        ),
        migrations.AddField(
            model_name='serie',
            name='versions',
            field=models.ManyToManyField(null=True, related_name='series_versions', to='cineseries.Version'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='film',
            name='cinemas',
            field=models.ManyToManyField(null=True, related_name='films_cinemas', to='cineseries.Cinema'),
        ),
        migrations.AlterField(
            model_name='film',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cineseries.Classification'),
        ),
        migrations.AlterField(
            model_name='ouverture',
            name='cinemas',
            field=models.ManyToManyField(null=True, related_name='ouvertures_cinemas', to='cineseries.Cinema'),
        ),
    ]
