# Generated by Django 3.0.4 on 2020-04-17 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cineseries', '0012_auto_20200417_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cinemas',
            field=models.ManyToManyField(related_name='films_cinemas', to='cineseries.Cinema'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='films_genres', to='cineseries.Genre'),
        ),
        migrations.AlterField(
            model_name='ouverture',
            name='cinemas',
            field=models.ManyToManyField(related_name='ouvertures_cinemas', to='cineseries.Cinema'),
        ),
        migrations.AlterField(
            model_name='seancesfilm',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Version'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genres',
            field=models.ManyToManyField(related_name='series_genres', to='cineseries.Genre'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='versions',
            field=models.ManyToManyField(related_name='series_versions', to='cineseries.Version'),
        ),
        migrations.CreateModel(
            name='Critique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(verbose_name='Note attribuée')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('episodes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Episode')),
                ('films', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Film')),
                ('saisons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Saison')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Serie')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Critique',
                'ordering': ['films'],
            },
        ),
    ]
