# Generated by Django 3.0.4 on 2020-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0013_auto_20200417_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteur',
            name='pays_naissance',
            field=models.CharField(max_length=20, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='realisateur',
            name='pays_naissance',
            field=models.CharField(max_length=20, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='biographie',
            field=models.TextField(null=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='realisateur',
            name='biographie',
            field=models.TextField(null=True, verbose_name='Biographie'),
        ),
    ]
