# Generated by Django 3.0.4 on 2020-04-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0014_auto_20200417_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acteur',
            name='nb_films',
        ),
        migrations.RemoveField(
            model_name='realisateur',
            name='nb_films',
        ),
        migrations.AddField(
            model_name='acteur',
            name='episodes',
            field=models.ManyToManyField(related_name='acteurs_episodes', to='cineseries.Episode'),
        ),
        migrations.AddField(
            model_name='acteur',
            name='films',
            field=models.ManyToManyField(related_name='acteurs_films', to='cineseries.Film'),
        ),
        migrations.AddField(
            model_name='realisateur',
            name='episodes',
            field=models.ManyToManyField(related_name='realisateurs_episodes', to='cineseries.Episode'),
        ),
        migrations.AddField(
            model_name='realisateur',
            name='films',
            field=models.ManyToManyField(related_name='realisateurs_films', to='cineseries.Film'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='fermeture_exceptionnelle',
            field=models.TextField(max_length=100, null=True, verbose_name='Fermeture Exceptionnelle'),
        ),
    ]
