# Generated by Django 3.0.4 on 2020-04-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0016_auto_20200417_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seancesfilm',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Version'),
        ),
    ]
