# Generated by Django 3.0.4 on 2020-04-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0017_auto_20200417_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critique',
            options={'ordering': ['users'], 'verbose_name': 'Critique'},
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='episode',
            new_name='episodes',
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='film',
            new_name='films',
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='saison',
            new_name='saisons',
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='serie',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='user',
            new_name='users',
        ),
    ]
