# Generated by Django 3.0.4 on 2020-04-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0018_auto_20200417_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critique',
            options={'ordering': ['user'], 'verbose_name': 'Critique'},
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='episodes',
            new_name='episode',
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='films',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='saisons',
            new_name='saison',
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='series',
            new_name='serie',
        ),
        migrations.RenameField(
            model_name='critique',
            old_name='users',
            new_name='user',
        ),
    ]
