# Generated by Django 3.0.4 on 2020-04-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0019_auto_20200417_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Critique',
        ),
    ]
