# Generated by Django 3.0.4 on 2020-04-17 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cineseries', '0020_delete_critique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(verbose_name='Note attribuée')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Episode')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Film')),
                ('saison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Saison')),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cineseries.Serie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Critique',
                'ordering': ['user'],
            },
        ),
    ]
