# Generated by Django 3.0.4 on 2020-04-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cineseries', '0021_critique'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='saison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cineseries.Saison'),
        ),
        migrations.AddField(
            model_name='saison',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cineseries.Serie'),
        ),
    ]
